name: porter/porter-canary
on:
  push:
    branches:
      - main
      - release/*
jobs:
  build_pipelinesrelease_template:
    name: build_pipelinesrelease_template
    uses: ./.github/workflows/build_pipelinesrelease_template.yml  
    with:
      registry: ghcr.io/kurtschenk
      shouldPublish: true
      skipTests: true
#      PORTER_RELEASE_REPOSITORY: ghcr.io/kurtschenk/porter
    secrets: inherit
